version: '3'

services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    container_name: client
    volumes:
      - ./client:/code/client
    ports:
      - "13000:3000"
    tty: true
    stdin_open: true
#    networks:
#      - dothecasting

  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: server
    volumes:
      - ./server:/code/server
    ports:
      - "18080:8080"
      - "12345:2345"
    depends_on:
      - db
    tty: true
    stdin_open: true
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
#    networks:
#      - dothecasting

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: db
    hostname: db
    ports:
      - "13306:3306"
    env_file:
      - ./docker/db/env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - "./mysql_data/mysql:/var/lib/mysql"
      - "./docker/db/my.conf:/etc/mysql/my.conf"
      - "./docker/db/init/:/docker-entrypoint-initdb.d"

networks:
  dothecasting:
    external: true